version: "3.8"
services:
  api:
    # image: dontelmo/kudos_api/
    networks:
      - kudos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/database
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db

  db:
    networks:
      - kudos
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  kudos:
    driver: bridge
